language: node_js
node_js:
- 10.9.0
install:
  - npm install -g codecov
cache:
  directories:
    - node_modules
script:
   - npm run lint
   - npm run test
after_script:
  - npm run report-coverage
